url: https://wbsllc.github.io
baseurl: /website/

# Site settings
title: Worthington Behavioral Services
email: jessica@worthingtonbehavioral.com
description: "ABA."

# Team names, titles and social links
people:
- name: Jessica, BCBA
  pic: 1
  position: Founder and Owner
  social:
    - title: email
      url: #
    - title: linkedin
      url: #

- name: Janet, PHR, SHRM-CP 
  pic: 2
  position: Human Resources Coordinator
  social:
    - title: email
      url: #
    - title: linkedin
      url: #

- name: Mary
  pic: 3
  position: Community Outreach Coordinator
  social:
    - title: email
      url: #
    - title: linkedin
      url: #
   
- name: Megan
  pic: 4
  position: Community Outreach Coordinator
  social:
    - title: email
      url: #
    - title: linkedin
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: http://instagram.com/wbsllc
  - title: facebook
    url: http://facebook.com/wbsllc

# Postal address (add as many lines as necessary)
address:
  - line: PO Box #170845
  - line: Milwaukee, WI 53217-4504

# Build settings
markdown: kramdown
permalink: pretty
