url: https://wbsllc.github.io
baseurl: /website/

# Site settings
title: Worthington Behavioral Services
email: jessica@worthingtonbehavioral.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Jessica
  pic: 1
  position: Founder and BCBA
  social:
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Janet
  pic: 2
  position: Human Resources Coordinator
  social:
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Mary
  pic: 3
  position: Community Outreach Coordinator
  social:
    - title: facebook
      url: #
    - title: linkedin
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: http://twitter.com/wbsllc
  - title: facebook
    url: http://facebook.com/wbsllc

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
